[[ssh-keys]]
item = "Raven SSH Key"
vault = "Raven"

[[ssh-keys]]
item = "Watney SSH Key"
vault = "Watney"

[[ssh-keys]]
item = "SSH Key"
vault = "Terminal Secrets"

[[ssh-keys]]
item = "Linode SSH"
vault = "Personal Infra"
