[font]
size = 14
[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "F20"

[window]
option_as_alt = "Both"
opacity = 0.95
blur = true

[colors]
transparent_background_colors = true
